package com.mapper.auto;

import com.model.auto.Amount;
import com.model.auto.AmountExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AmountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    long countByExample(AmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    int deleteByExample(AmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    int insert(Amount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    int insertSelective(Amount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    List<Amount> selectByExample(AmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    Amount selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    int updateByExampleSelective(@Param("record") Amount record, @Param("example") AmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    int updateByExample(@Param("record") Amount record, @Param("example") AmountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    int updateByPrimaryKeySelective(Amount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    int updateByPrimaryKey(Amount record);
}