package com.mapper.auto;

import com.model.auto.Column;
import com.model.auto.ColumnExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ColumnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..column
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    long countByExample(ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..column
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int deleteByExample(ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..column
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..column
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int insert(Column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..column
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int insertSelective(Column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..column
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    List<Column> selectByExample(ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..column
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    Column selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..column
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") Column record, @Param("example") ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..column
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int updateByExample(@Param("record") Column record, @Param("example") ColumnExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..column
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int updateByPrimaryKeySelective(Column record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..column
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int updateByPrimaryKey(Column record);
}