package com.mapper.auto;

import com.model.auto.Content;
import com.model.auto.ContentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    long countByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int deleteByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int insert(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int insertSelective(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    List<Content> selectByExample(ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    Content selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int updateByExampleSelective(@Param("record") Content record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int updateByExample(@Param("record") Content record, @Param("example") ContentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int updateByPrimaryKeySelective(Content record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    int updateByPrimaryKey(Content record);
}