package com.mapper.auto;

import com.model.auto.Species;
import com.model.auto.SpeciesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SpeciesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    int countByExample(SpeciesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    int deleteByExample(SpeciesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    int insert(Species record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    int insertSelective(Species record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    List<Species> selectByExample(SpeciesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    Species selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    int updateByExampleSelective(@Param("record") Species record, @Param("example") SpeciesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    int updateByExample(@Param("record") Species record, @Param("example") SpeciesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    int updateByPrimaryKeySelective(Species record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    int updateByPrimaryKey(Species record);
}