package com.model.auto;

import java.util.Date;

public class Amount {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..amount.id
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..amount.account_number
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    private Long accountNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..amount.species_number
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    private Long speciesNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..amount.recorder
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    private Long recorder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..amount.amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    private Long amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..amount.record_date
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    private Long recordDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..amount.create_time
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..amount.update_time
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..amount.isdel
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..amount.type
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    private Integer type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..amount.id
     *
     * @return the value of bill..amount.id
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..amount.id
     *
     * @param id the value for bill..amount.id
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..amount.account_number
     *
     * @return the value of bill..amount.account_number
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public Long getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..amount.account_number
     *
     * @param accountNumber the value for bill..amount.account_number
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public void setAccountNumber(Long accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..amount.species_number
     *
     * @return the value of bill..amount.species_number
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public Long getSpeciesNumber() {
        return speciesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..amount.species_number
     *
     * @param speciesNumber the value for bill..amount.species_number
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public void setSpeciesNumber(Long speciesNumber) {
        this.speciesNumber = speciesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..amount.recorder
     *
     * @return the value of bill..amount.recorder
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public Long getRecorder() {
        return recorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..amount.recorder
     *
     * @param recorder the value for bill..amount.recorder
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public void setRecorder(Long recorder) {
        this.recorder = recorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..amount.amount
     *
     * @return the value of bill..amount.amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public Long getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..amount.amount
     *
     * @param amount the value for bill..amount.amount
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public void setAmount(Long amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..amount.record_date
     *
     * @return the value of bill..amount.record_date
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public Long getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..amount.record_date
     *
     * @param recordDate the value for bill..amount.record_date
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public void setRecordDate(Long recordDate) {
        this.recordDate = recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..amount.create_time
     *
     * @return the value of bill..amount.create_time
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..amount.create_time
     *
     * @param createTime the value for bill..amount.create_time
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..amount.update_time
     *
     * @return the value of bill..amount.update_time
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..amount.update_time
     *
     * @param updateTime the value for bill..amount.update_time
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..amount.isdel
     *
     * @return the value of bill..amount.isdel
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..amount.isdel
     *
     * @param isdel the value for bill..amount.isdel
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..amount.type
     *
     * @return the value of bill..amount.type
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..amount.type
     *
     * @param type the value for bill..amount.type
     *
     * @mbg.generated Wed May 08 14:20:45 CST 2019
     */
    public void setType(Integer type) {
        this.type = type;
    }
}