package com.model.auto;

import java.util.Date;

public class Column {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..column.id
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..column.column_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Long columnNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..column.column_name
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private String columnName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..column.object_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Long objectNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..column.column_type
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Integer columnType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..column.key
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private String key;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..column.create_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..column.update_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..column.isdel
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Boolean isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..column.id
     *
     * @return the value of bill..column.id
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..column.id
     *
     * @param id the value for bill..column.id
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..column.column_number
     *
     * @return the value of bill..column.column_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Long getColumnNumber() {
        return columnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..column.column_number
     *
     * @param columnNumber the value for bill..column.column_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setColumnNumber(Long columnNumber) {
        this.columnNumber = columnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..column.column_name
     *
     * @return the value of bill..column.column_name
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public String getColumnName() {
        return columnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..column.column_name
     *
     * @param columnName the value for bill..column.column_name
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setColumnName(String columnName) {
        this.columnName = columnName == null ? null : columnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..column.object_number
     *
     * @return the value of bill..column.object_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Long getObjectNumber() {
        return objectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..column.object_number
     *
     * @param objectNumber the value for bill..column.object_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setObjectNumber(Long objectNumber) {
        this.objectNumber = objectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..column.column_type
     *
     * @return the value of bill..column.column_type
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Integer getColumnType() {
        return columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..column.column_type
     *
     * @param columnType the value for bill..column.column_type
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setColumnType(Integer columnType) {
        this.columnType = columnType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..column.key
     *
     * @return the value of bill..column.key
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public String getKey() {
        return key;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..column.key
     *
     * @param key the value for bill..column.key
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setKey(String key) {
        this.key = key == null ? null : key.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..column.create_time
     *
     * @return the value of bill..column.create_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..column.create_time
     *
     * @param createTime the value for bill..column.create_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..column.update_time
     *
     * @return the value of bill..column.update_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..column.update_time
     *
     * @param updateTime the value for bill..column.update_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..column.isdel
     *
     * @return the value of bill..column.isdel
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..column.isdel
     *
     * @param isdel the value for bill..column.isdel
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }
}