package com.model.auto;

import java.util.Date;

public class Content {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..content.id
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..content.object_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Long objectNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..content.column_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Long columnNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..content.content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..content.row_tag
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Integer rowTag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..content.create_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..content.update_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..content.isdel
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Boolean isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..content.id
     *
     * @return the value of bill..content.id
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..content.id
     *
     * @param id the value for bill..content.id
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..content.object_number
     *
     * @return the value of bill..content.object_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Long getObjectNumber() {
        return objectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..content.object_number
     *
     * @param objectNumber the value for bill..content.object_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setObjectNumber(Long objectNumber) {
        this.objectNumber = objectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..content.column_number
     *
     * @return the value of bill..content.column_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Long getColumnNumber() {
        return columnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..content.column_number
     *
     * @param columnNumber the value for bill..content.column_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setColumnNumber(Long columnNumber) {
        this.columnNumber = columnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..content.content
     *
     * @return the value of bill..content.content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..content.content
     *
     * @param content the value for bill..content.content
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..content.row_tag
     *
     * @return the value of bill..content.row_tag
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Integer getRowTag() {
        return rowTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..content.row_tag
     *
     * @param rowTag the value for bill..content.row_tag
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setRowTag(Integer rowTag) {
        this.rowTag = rowTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..content.create_time
     *
     * @return the value of bill..content.create_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..content.create_time
     *
     * @param createTime the value for bill..content.create_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..content.update_time
     *
     * @return the value of bill..content.update_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..content.update_time
     *
     * @param updateTime the value for bill..content.update_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..content.isdel
     *
     * @return the value of bill..content.isdel
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..content.isdel
     *
     * @param isdel the value for bill..content.isdel
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }
}