package com.model.auto;

import java.util.Date;

public class Object {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..object.id
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..object.object_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Long objectNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..object.object_name
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private String objectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..object.create_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..object.update_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..object.isdel
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Boolean isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..object.creator_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    private Long creatorNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..object.id
     *
     * @return the value of bill..object.id
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..object.id
     *
     * @param id the value for bill..object.id
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..object.object_number
     *
     * @return the value of bill..object.object_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Long getObjectNumber() {
        return objectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..object.object_number
     *
     * @param objectNumber the value for bill..object.object_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setObjectNumber(Long objectNumber) {
        this.objectNumber = objectNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..object.object_name
     *
     * @return the value of bill..object.object_name
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public String getObjectName() {
        return objectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..object.object_name
     *
     * @param objectName the value for bill..object.object_name
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setObjectName(String objectName) {
        this.objectName = objectName == null ? null : objectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..object.create_time
     *
     * @return the value of bill..object.create_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..object.create_time
     *
     * @param createTime the value for bill..object.create_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..object.update_time
     *
     * @return the value of bill..object.update_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..object.update_time
     *
     * @param updateTime the value for bill..object.update_time
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..object.isdel
     *
     * @return the value of bill..object.isdel
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..object.isdel
     *
     * @param isdel the value for bill..object.isdel
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..object.creator_number
     *
     * @return the value of bill..object.creator_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public Long getCreatorNumber() {
        return creatorNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..object.creator_number
     *
     * @param creatorNumber the value for bill..object.creator_number
     *
     * @mbg.generated Tue Apr 02 14:54:01 CST 2019
     */
    public void setCreatorNumber(Long creatorNumber) {
        this.creatorNumber = creatorNumber;
    }
}