package com.model.auto;

import java.util.Date;

public class Species {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..species.id
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..species.species_number
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    private Long speciesNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..species.account_number
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    private Long accountNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..species.species_name
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    private String speciesName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..species.species_type
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    private Integer speciesType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..species.creator
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    private Long creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..species.create_time
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..species.update_time
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..species.isdel
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    private Boolean isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..species.id
     *
     * @return the value of bill..species.id
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..species.id
     *
     * @param id the value for bill..species.id
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..species.species_number
     *
     * @return the value of bill..species.species_number
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public Long getSpeciesNumber() {
        return speciesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..species.species_number
     *
     * @param speciesNumber the value for bill..species.species_number
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void setSpeciesNumber(Long speciesNumber) {
        this.speciesNumber = speciesNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..species.account_number
     *
     * @return the value of bill..species.account_number
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public Long getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..species.account_number
     *
     * @param accountNumber the value for bill..species.account_number
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void setAccountNumber(Long accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..species.species_name
     *
     * @return the value of bill..species.species_name
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public String getSpeciesName() {
        return speciesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..species.species_name
     *
     * @param speciesName the value for bill..species.species_name
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void setSpeciesName(String speciesName) {
        this.speciesName = speciesName == null ? null : speciesName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..species.species_type
     *
     * @return the value of bill..species.species_type
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public Integer getSpeciesType() {
        return speciesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..species.species_type
     *
     * @param speciesType the value for bill..species.species_type
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void setSpeciesType(Integer speciesType) {
        this.speciesType = speciesType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..species.creator
     *
     * @return the value of bill..species.creator
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..species.creator
     *
     * @param creator the value for bill..species.creator
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..species.create_time
     *
     * @return the value of bill..species.create_time
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..species.create_time
     *
     * @param createTime the value for bill..species.create_time
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..species.update_time
     *
     * @return the value of bill..species.update_time
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..species.update_time
     *
     * @param updateTime the value for bill..species.update_time
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..species.isdel
     *
     * @return the value of bill..species.isdel
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..species.isdel
     *
     * @param isdel the value for bill..species.isdel
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }
}