package com.model.auto;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SpeciesExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public SpeciesExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberIsNull() {
            addCriterion("species_number is null");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberIsNotNull() {
            addCriterion("species_number is not null");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberEqualTo(Long value) {
            addCriterion("species_number =", value, "speciesNumber");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberNotEqualTo(Long value) {
            addCriterion("species_number <>", value, "speciesNumber");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberGreaterThan(Long value) {
            addCriterion("species_number >", value, "speciesNumber");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("species_number >=", value, "speciesNumber");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberLessThan(Long value) {
            addCriterion("species_number <", value, "speciesNumber");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberLessThanOrEqualTo(Long value) {
            addCriterion("species_number <=", value, "speciesNumber");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberIn(List<Long> values) {
            addCriterion("species_number in", values, "speciesNumber");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberNotIn(List<Long> values) {
            addCriterion("species_number not in", values, "speciesNumber");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberBetween(Long value1, Long value2) {
            addCriterion("species_number between", value1, value2, "speciesNumber");
            return (Criteria) this;
        }

        public Criteria andSpeciesNumberNotBetween(Long value1, Long value2) {
            addCriterion("species_number not between", value1, value2, "speciesNumber");
            return (Criteria) this;
        }

        public Criteria andAccountNumberIsNull() {
            addCriterion("account_number is null");
            return (Criteria) this;
        }

        public Criteria andAccountNumberIsNotNull() {
            addCriterion("account_number is not null");
            return (Criteria) this;
        }

        public Criteria andAccountNumberEqualTo(Long value) {
            addCriterion("account_number =", value, "accountNumber");
            return (Criteria) this;
        }

        public Criteria andAccountNumberNotEqualTo(Long value) {
            addCriterion("account_number <>", value, "accountNumber");
            return (Criteria) this;
        }

        public Criteria andAccountNumberGreaterThan(Long value) {
            addCriterion("account_number >", value, "accountNumber");
            return (Criteria) this;
        }

        public Criteria andAccountNumberGreaterThanOrEqualTo(Long value) {
            addCriterion("account_number >=", value, "accountNumber");
            return (Criteria) this;
        }

        public Criteria andAccountNumberLessThan(Long value) {
            addCriterion("account_number <", value, "accountNumber");
            return (Criteria) this;
        }

        public Criteria andAccountNumberLessThanOrEqualTo(Long value) {
            addCriterion("account_number <=", value, "accountNumber");
            return (Criteria) this;
        }

        public Criteria andAccountNumberIn(List<Long> values) {
            addCriterion("account_number in", values, "accountNumber");
            return (Criteria) this;
        }

        public Criteria andAccountNumberNotIn(List<Long> values) {
            addCriterion("account_number not in", values, "accountNumber");
            return (Criteria) this;
        }

        public Criteria andAccountNumberBetween(Long value1, Long value2) {
            addCriterion("account_number between", value1, value2, "accountNumber");
            return (Criteria) this;
        }

        public Criteria andAccountNumberNotBetween(Long value1, Long value2) {
            addCriterion("account_number not between", value1, value2, "accountNumber");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameIsNull() {
            addCriterion("species_name is null");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameIsNotNull() {
            addCriterion("species_name is not null");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameEqualTo(String value) {
            addCriterion("species_name =", value, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameNotEqualTo(String value) {
            addCriterion("species_name <>", value, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameGreaterThan(String value) {
            addCriterion("species_name >", value, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameGreaterThanOrEqualTo(String value) {
            addCriterion("species_name >=", value, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameLessThan(String value) {
            addCriterion("species_name <", value, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameLessThanOrEqualTo(String value) {
            addCriterion("species_name <=", value, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameLike(String value) {
            addCriterion("species_name like", value, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameNotLike(String value) {
            addCriterion("species_name not like", value, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameIn(List<String> values) {
            addCriterion("species_name in", values, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameNotIn(List<String> values) {
            addCriterion("species_name not in", values, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameBetween(String value1, String value2) {
            addCriterion("species_name between", value1, value2, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesNameNotBetween(String value1, String value2) {
            addCriterion("species_name not between", value1, value2, "speciesName");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeIsNull() {
            addCriterion("species_type is null");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeIsNotNull() {
            addCriterion("species_type is not null");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeEqualTo(Integer value) {
            addCriterion("species_type =", value, "speciesType");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeNotEqualTo(Integer value) {
            addCriterion("species_type <>", value, "speciesType");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeGreaterThan(Integer value) {
            addCriterion("species_type >", value, "speciesType");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("species_type >=", value, "speciesType");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeLessThan(Integer value) {
            addCriterion("species_type <", value, "speciesType");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeLessThanOrEqualTo(Integer value) {
            addCriterion("species_type <=", value, "speciesType");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeIn(List<Integer> values) {
            addCriterion("species_type in", values, "speciesType");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeNotIn(List<Integer> values) {
            addCriterion("species_type not in", values, "speciesType");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeBetween(Integer value1, Integer value2) {
            addCriterion("species_type between", value1, value2, "speciesType");
            return (Criteria) this;
        }

        public Criteria andSpeciesTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("species_type not between", value1, value2, "speciesType");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNull() {
            addCriterion("creator is null");
            return (Criteria) this;
        }

        public Criteria andCreatorIsNotNull() {
            addCriterion("creator is not null");
            return (Criteria) this;
        }

        public Criteria andCreatorEqualTo(Long value) {
            addCriterion("creator =", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotEqualTo(Long value) {
            addCriterion("creator <>", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThan(Long value) {
            addCriterion("creator >", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorGreaterThanOrEqualTo(Long value) {
            addCriterion("creator >=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThan(Long value) {
            addCriterion("creator <", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorLessThanOrEqualTo(Long value) {
            addCriterion("creator <=", value, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorIn(List<Long> values) {
            addCriterion("creator in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotIn(List<Long> values) {
            addCriterion("creator not in", values, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorBetween(Long value1, Long value2) {
            addCriterion("creator between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreatorNotBetween(Long value1, Long value2) {
            addCriterion("creator not between", value1, value2, "creator");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNull() {
            addCriterion("isdel is null");
            return (Criteria) this;
        }

        public Criteria andIsdelIsNotNull() {
            addCriterion("isdel is not null");
            return (Criteria) this;
        }

        public Criteria andIsdelEqualTo(Boolean value) {
            addCriterion("isdel =", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotEqualTo(Boolean value) {
            addCriterion("isdel <>", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThan(Boolean value) {
            addCriterion("isdel >", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelGreaterThanOrEqualTo(Boolean value) {
            addCriterion("isdel >=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThan(Boolean value) {
            addCriterion("isdel <", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelLessThanOrEqualTo(Boolean value) {
            addCriterion("isdel <=", value, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelIn(List<Boolean> values) {
            addCriterion("isdel in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotIn(List<Boolean> values) {
            addCriterion("isdel not in", values, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelBetween(Boolean value1, Boolean value2) {
            addCriterion("isdel between", value1, value2, "isdel");
            return (Criteria) this;
        }

        public Criteria andIsdelNotBetween(Boolean value1, Boolean value2) {
            addCriterion("isdel not between", value1, value2, "isdel");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill..species
     *
     * @mbggenerated do_not_delete_during_merge Sat Apr 20 10:03:02 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bill..species
     *
     * @mbggenerated Sat Apr 20 10:03:02 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}