package com.model.auto;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user.id
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user.user_number
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    private Long userNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user.password
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user.create_time
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user.update_time
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user.nickname
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    private String nickname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user.id
     *
     * @return the value of bill..user.id
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user.id
     *
     * @param id the value for bill..user.id
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user.user_number
     *
     * @return the value of bill..user.user_number
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public Long getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user.user_number
     *
     * @param userNumber the value for bill..user.user_number
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public void setUserNumber(Long userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user.password
     *
     * @return the value of bill..user.password
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user.password
     *
     * @param password the value for bill..user.password
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user.create_time
     *
     * @return the value of bill..user.create_time
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user.create_time
     *
     * @param createTime the value for bill..user.create_time
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user.update_time
     *
     * @return the value of bill..user.update_time
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user.update_time
     *
     * @param updateTime the value for bill..user.update_time
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user.nickname
     *
     * @return the value of bill..user.nickname
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user.nickname
     *
     * @param nickname the value for bill..user.nickname
     *
     * @mbg.generated Thu Feb 21 10:25:58 CST 2019
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }
}