package com.model.auto;

import java.util.Date;

public class UserAccountRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user_account_relation.id
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user_account_relation.user_number
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    private Long userNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user_account_relation.account_number
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    private Long accountNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user_account_relation.account_name
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user_account_relation.permission
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    private Integer permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user_account_relation.create_time
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user_account_relation.update_time
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bill..user_account_relation.isdel
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    private Boolean isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user_account_relation.id
     *
     * @return the value of bill..user_account_relation.id
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user_account_relation.id
     *
     * @param id the value for bill..user_account_relation.id
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user_account_relation.user_number
     *
     * @return the value of bill..user_account_relation.user_number
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public Long getUserNumber() {
        return userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user_account_relation.user_number
     *
     * @param userNumber the value for bill..user_account_relation.user_number
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public void setUserNumber(Long userNumber) {
        this.userNumber = userNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user_account_relation.account_number
     *
     * @return the value of bill..user_account_relation.account_number
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public Long getAccountNumber() {
        return accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user_account_relation.account_number
     *
     * @param accountNumber the value for bill..user_account_relation.account_number
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public void setAccountNumber(Long accountNumber) {
        this.accountNumber = accountNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user_account_relation.account_name
     *
     * @return the value of bill..user_account_relation.account_name
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user_account_relation.account_name
     *
     * @param accountName the value for bill..user_account_relation.account_name
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user_account_relation.permission
     *
     * @return the value of bill..user_account_relation.permission
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public Integer getPermission() {
        return permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user_account_relation.permission
     *
     * @param permission the value for bill..user_account_relation.permission
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public void setPermission(Integer permission) {
        this.permission = permission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user_account_relation.create_time
     *
     * @return the value of bill..user_account_relation.create_time
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user_account_relation.create_time
     *
     * @param createTime the value for bill..user_account_relation.create_time
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user_account_relation.update_time
     *
     * @return the value of bill..user_account_relation.update_time
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user_account_relation.update_time
     *
     * @param updateTime the value for bill..user_account_relation.update_time
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bill..user_account_relation.isdel
     *
     * @return the value of bill..user_account_relation.isdel
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public Boolean getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bill..user_account_relation.isdel
     *
     * @param isdel the value for bill..user_account_relation.isdel
     *
     * @mbg.generated Sat Apr 20 12:00:30 CST 2019
     */
    public void setIsdel(Boolean isdel) {
        this.isdel = isdel;
    }
}